services:
  postgres:
    image: postgres:15@sha256:2d8059176e789c849701fc06d3f7834d4f6db52b74c89f7f3517c4540a3c38bd
    environment:
      - POSTGRES_DB=image_sass
      - POSTGRES_USER=image_sass
      - POSTGRES_PASSWORD=image_sass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  db_data:
