import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { trpcClient, trpcClientReact } from "@/utils/api";
import "./globals.css";
import { TRPCProvider } from "./TrpcProver";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TRPCProvider> {children}</TRPCProvider>
      </body>
    </html>
  );
}
